[package]
name = "walle"
version = "0.1.0"
authors = ["Sonny Scroggin"]
edition = "2021"

[lib]
name = "walle"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.30"
ethers = "2.0"
tempfile = "3.10"
rand = "0.8.5"
